<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 80px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Članovi</h1>

        <?php if (isset($clanovi)) : ?>
            <table>
                <tr>
                    <th><b>Ime</b></th>
                    <th><b>Prezime</b></th>
                    <th></th>
                </tr>
            <?php
                foreach ($clanovi as $clan){ ?>
                    <tr>
                        <td><?= $clan["ime"] ?></td>
                        <td><?= $clan["prezime"] ?></td>
                        <td><a href="uplata/<?= $clan["id"]?>" target="_blank">Uplati</a></td>
                    </tr>
               <?php }
            ?>
            </table>
        <?php else: ?>
            <?php 
                echo "<pre>"; var_dump("error"); die;
            ?>
        <?php endif; ?>
    </body>
</html>
