<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Članovi</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="/css/style.css">
    </head>
    <body>
        <header>
            <ul class="menu">
                <li>
                    <a href="/clanovi">Članovi</a>
                    <span></span>
                </li>
                <li>
                    <?php if($sesija->exists('user_session')){ ?><a href="/logout">Logout</a> <?php }
                    else{ ?><a href="/login">Login</a> <?php } ?>
                    <span></span>
                </li>
            </ul>
        </header>
        <h1>Članovi</h1>
        <div class="container">
            <br>
        <input type="search" class="light-table-filter" data-table="order-table" placeholder="Pretraga" />
            <br>
        <?php if (isset($clanovi)) : ?>
            <table class="order-table">
                <tr>
                    <th><b>Ime</b></th>
                    <th><b>Prezime</b></th>
                    <th></th>
                </tr>
            <?php
                foreach ($clanovi as $clan){ ?>
                    <tr>
                        <td><?= $clan["ime"] ?></td>
                        <td><?= $clan["prezime"] ?></td>
                        <td><a href="uplata/<?= $clan["id"]?>" target="_blank">Uplati</a></td>
                    </tr>
               <?php }
            ?>
            </table>
        </div>
        <?php else: ?>
            <?php 
                echo "<pre>"; var_dump("error"); die;
            ?>
        <?php endif; ?>
    </body>
</html>

<script>
    (function(document) {
        'use strict';

        var LightTableFilter = (function(Arr) {

            var _input;

            function _onInputEvent(e) {
                _input = e.target;
                var tables = document.getElementsByClassName(_input.getAttribute('data-table'));
                Arr.forEach.call(tables, function(table) {
                    Arr.forEach.call(table.tBodies, function(tbody) {
                        Arr.forEach.call(tbody.rows, _filter);
                    });
                });
            }

            function _filter(row) {
                var text = row.textContent.toLowerCase(), val = _input.value.toLowerCase();
                row.style.display = text.indexOf(val) === -1 ? 'none' : 'table-row';
            }

            return {
                init: function() {
                    var inputs = document.getElementsByClassName('light-table-filter');
                    Arr.forEach.call(inputs, function(input) {
                        input.oninput = _onInputEvent;
                    });
                }
            };
        })(Array.prototype);

        document.addEventListener('readystatechange', function() {
            if (document.readyState === 'complete') {
                LightTableFilter.init();
            }
        });

    })(document);
</script>
