<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Članovi</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="/css/style.css">
    </head>
    <body>
        <header>
            <ul class="menu">
                <li>
                    <a href="/clanovi">Članovi</a>
                    <span></span>
                </li>
                <li>
                    <?php if($sesija->exists('user_session')){ ?><a href="/logout">Logout</a> <?php }
                    else{ ?><a href="/login">Login</a> <?php } ?>
                    <span></span>
                </li>
            </ul>
        </header>
        <h1>Članovi</h1>

        <?php if (isset($clanovi)) : ?>
            <table>
                <tr>
                    <th><b>Ime</b></th>
                    <th><b>Prezime</b></th>
                    <th></th>
                </tr>
            <?php
                foreach ($clanovi as $clan){ ?>
                    <tr>
                        <td><?= $clan["ime"] ?></td>
                        <td><?= $clan["prezime"] ?></td>
                        <td><a href="uplata/<?= $clan["id"]?>" target="_blank">Uplati</a></td>
                    </tr>
               <?php }
            ?>
            </table>
        <?php else: ?>
            <?php 
                echo "<pre>"; var_dump("error"); die;
            ?>
        <?php endif; ?>
    </body>
</html>
