<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Login</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/css/login.css">
    </head>
    <body>
        <div class="login">
            <div class="login-triangle"></div>

            <h2 class="login-header">Login</h2>

            <form class="login-container" method="post">
                <p><input type="text" name="username" placeholder="Email or username"></p>
                <p><input type="password" name="password" placeholder="Password"></p>
                <p><input type="submit" value="Login"></p>
            </form>
        </div>
    </body>
</html>
