<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Evidencija o uplati</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
<header>
    <ul class="menu">
        <li>
            <a href="/uplata">Uplate</a>
            <span></span>
        </li>
        <li>
            <a href="/clanovi">Članovi</a>
            <span></span>
        </li>
        <li>
            <?php if($sesija->exists('user_session')){ ?><a href="/logout">Logout</a> <?php }
            else{ ?><a href="/login">Login</a> <?php } ?>
            <span></span>
        </li>
    </ul>
</header>
<h1>Uplata</h1>
<h2><?= $clan["ime"] . " " . $clan["prezime"] ?></h2>
<div id="uplate">
    <?php
    foreach ($uplate as $uplata){ ?>
        <div><span><?= $uplata["mjesec"] ?></span> - <span><?= $uplata["godina"] ?></span></div>
    <?php }
    ?>

</div>
</body>
</html>
